version: '3.4'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admins
      - INFLUXDB_ADMIN_PASSWORD=pass
    volumes:
      # Mount data directory for persistent.
      - ./influxdb/__data:/var/lib/influxdb
  chronograf:
    image: chronograf:latest
    ports:
      - '8888:8888'
    volumes:
      - ./__chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=admin
      - INFLUXDB_PASSWORD=pass