version: '3.1'

services:
  redis-cluster:
    container_name: redis
    image: grokzen/redis-cluster:6.0.8
    ports:
      - "7000-7005:7000-7005"
    environment:
      - IP=0.0.0.0
      - INITIAL_PORT=7000
